basePath: /v3
definitions:
  model.APIData:
    properties:
      error:
        description: Error message
        type: string
      last_page:
        description: Last page of requested board
        type: integer
      posts:
        description: Data of board
        items:
          $ref: '#/definitions/model.Board'
        type: array
      status_code:
        description: Status code of request
        type: integer
    type: object
  model.ApiArticle:
    properties:
      article_url:
        type: string
      content:
        type: string
      error:
        description: Error message
        type: string
      files:
        items:
          $ref: '#/definitions/model.Files'
        type: array
      id:
        type: string
      status_code:
        description: Status code of request
        type: integer
      title:
        type: string
      write_date:
        type: string
      writer:
        type: string
    type: object
  model.Board:
    properties:
      id:
        type: string
      num:
        type: integer
      read_count:
        type: integer
      title:
        type: string
      write_date:
        type: string
      writer:
        type: string
    type: object
  model.Files:
    properties:
      file_name:
        type: string
      file_url:
        type: string
    type: object
info:
  contact:
    email: kongwoojin03@gmail.com
    name: Developer
  description: This is unofficial version of KOREATECH board REST API
  title: KOREATECH board REST API
  version: "1.0"
paths:
  /{department}/{board}:
    get:
      consumes:
      - application/json
      description: Get notice list
      parameters:
      - description: name of the department
        enum:
        - arch
        - cse
        - dorm
        - mse
        - ace
        - ide
        - ite
        - mechanical
        - mechatronics
        - school
        - sim
        in: path
        name: department
        required: true
        type: string
      - description: name of the board
        enum:
        - notice
        - free
        - job
        - pds
        - lecture
        - bachelor
        - scholar
        in: path
        name: board
        required: true
        type: string
      - description: page of board
        in: query
        name: page
        type: integer
      - description: items per page
        in: query
        name: num_of_items
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Get notice list
      tags:
      - Notice
  /{department}/{board}/search/title:
    get:
      consumes:
      - application/json
      description: Search article from specific board by title
      parameters:
      - description: name of the department
        enum:
        - arch
        - cse
        - dorm
        - mse
        - ace
        - ide
        - ite
        - mechanical
        - mechatronics
        - school
        - sim
        in: path
        name: department
        required: true
        type: string
      - description: name of the board
        enum:
        - notice
        - free
        - job
        - pds
        - lecture
        - bachelor
        - scholar
        in: path
        name: board
        required: true
        type: string
      - description: title
        in: query
        name: title
        required: true
        type: string
      - description: page of board
        in: query
        name: page
        type: integer
      - description: items per page
        in: query
        name: num_of_items
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ApiArticle'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Search article by title
      tags:
      - Notice
  /article:
    get:
      consumes:
      - application/json
      description: Get article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ApiArticle'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Get article
      tags:
      - Notice
swagger: "2.0"
